version: "3.7" 
services:
  # Web service layer & Application service layer
  php:
    build:
      context: .
    volumes:
      - "./src:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
  
  # Data persistence service layer
  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

volumes:
  db_data: